### PR TITLE
docs: add aspect ratio docs for CldImage component

### LINKED ISSUE #475: [Feature] Document aspectRatio contraints
Document the aspectRatio contraints wrt how and when it applies under the cldimage/config page

Per https://github.com/cloudinary-community/next-cloudinary/issues/352#issuecomment-2115636574

> hey @\antoinerousseau as it stands, and i think i need to update the documentation to reflect this, [aspectRatio doesn't get applied](https://github.com/cloudinary-community/cloudinary-util/blob/main/packages/url-loader/src/plugins/cropping.ts#L171) unless combined with a crop mode, for instance:
> 
> ```
> <CldImage
>   src="examples/mario_hkgavf"
>   width={2048}
>   height={1600}
>   aspectRatio="16:9"
>   alt="mario"
>   crop="fill"
> />
> ```
> 
> will give you:
> 
> https://res.cloudinary.com/colbycloud-examples/image/upload/c_fill,ar_16:9,w_3840,h_3000,g_auto/f_auto/q_auto/v1/examples/mario_hkgavf?_a=BAVFAaAO0
> 
> however that's not very useful because the width and the height prevent the aspect ratio from applying as a transformation
> 
> where `aspectRatio` really makes sense is when using the `fill` prop, such as:
> 
> ```
> <CldImage
>   src="examples/mario_hkgavf"
>   aspectRatio="16:9"
>   fill
>   alt="mario"
>   crop="fill"
> />
> ```
> 
> which would give you this:
> 
> https://res.cloudinary.com/colbycloud-examples/image/upload/c_fill,ar_16:9,w_2048,g_auto/f_auto/q_auto/v1/examples/mario_hkgavf?_a=BAVFAaAO0
> 
> the issue is that width and height are required props for the component. this is a Next Image component requirement that's passed along to this component and it's required to prevent layout shift when applied to the  
> but thats where the `fill` option comes in, which doesn't require a width and height, but then you control the size of the parent container which the image then "fills". this is a good use case for the `aspectRatio` prop in that regard
> 
> i'm open to feedback and ideas on this, as it's not outright intuitive with how that works. i'll create a ticket to update the docs to make this more clear to start

### PR DESCRIPTION
**Pull request by DevRish**
# Description

This PR adds documentation for the `aspectRatio` prop of the `CldImage` component, highlighting the constraints and cases where `aspectRatio` prop is applicable and will work properly.

The constraint is that `width` and `height` props are required by NextJS and `aspectRatio` prop does not function properly when they are set. So, for proper functioning of `aspectRatio`, the `fill` prop must also be present on the component, and `height` and `width` props must be absent.

More details [here](https://github.com/cloudinary-community/next-cloudinary/issues/475)

## Issue Ticket Number

Fixes #475 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Fix or improve the documentation
- [x] This change requires a documentation update

# Checklist

- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have created an [issue](https://github.com/cloudinary-community/next-cloudinary/issues) ticket for this PR
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/cloudinary-community/next-cloudinary/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have run tests locally to ensure they all pass
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by colbyfayock** [comment]
thanks @DevRish - i think the only thing missing here is mentioning about it requiring a specific crop mode

if you check this out, you can see where the code itself requires it: https://github.com/cloudinary-community/cloudinary-util/blob/main/packages/url-loader/src/plugins/cropping.ts#L185

**Comment by DevRish** [comment]
@colbyfayock  Thanks for reviewing and providing the code reference! I have made the necessary changes and also added some further explanation following [your comment](https://github.com/cloudinary-community/next-cloudinary/issues/475#issue-2300796995) on the issue. 

I also created a separate `Usage constraints` sub-section for it under the `aspectRatio` section to make it more readable.

**Comment by colbyfayock** [comment]
looks good to me! thanks @DevRish 

thanks for your contribution. this PR is eligible for free Cloudinary Hackatoberfest swag. Please send me an email at hacktoberfest@cloudinary.com with your name, GitHub username, and a link to the PR where I'll send further instructions.

Happy Hacktoberfest!

**Comment by colbyfayock** [comment]
@all-contributors please add @DevRish for doc

**Comment by DevRish** [comment]
@colbyfayock 

Thanks for adding me to the contribitor list! I have also sent the mail for the swags.

Happy Hacktoberfest!

**Pull request merged**
