### PR TITLE
feat: implement dynamic README values using markdown-magic & markdown-magic-package-json

### LINKED ISSUE #513: [Feature] Add current version in documentation
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Add the current version of the SDK in somewhere prominent.

In header? Top of sidebar?

This should be dynamically added based on the package version, not requiring it to be updated manually every time

### PR DESCRIPTION
**Pull request by vickywane**
# Description

This PR aims to close #513 by making changes to dynamically add release versions into the markdown documentation.

Fixes #513

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Fix or improve the documentation
- [x] This change requires a documentation update

# Checklist

- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have created an [issue](https://github.com/cloudinary-community/next-cloudinary/issues) ticket for this PR
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/cloudinary-community/next-cloudinary/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have run tests locally to ensure they all pass
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by vickywane** [comment]
@colbyfayock This PR isn't completed yet, however it has provided a sense of direction to solve this. 

I have tried using the `markdown-magic` and `markdown-magic-package-json` packages to dynamically inject values from the `package.json` file into the README file. This process will require executing the `generate-readme` command added to the `package.json` upon every successful release. ( this can be executed in the CI pipeline or commit hook to avoid manual work ).

At the moment, the `markdown-magic` and `markdown-magic-package-json` packages are not finding the specific values but I wanted to share this update to receive early feedback on this process. Also, I can try to remove the two packages and write a JS script to manually inject strings to the README file.

**Comment by colbyfayock** [comment]
hey @vickywane thanks for raising the PR

i think the goal here isn't necessarily the README it's to add the version number into the documentation website 

https://next.cloudinary.dev/

i was thinking we may be able to import the package.json from the package and reference the version number in the navigation or something

**Comment by vickywane** [comment]
> hey @vickywane thanks for raising the PR
> 
> i think the goal here isn't necessarily the README it's to add the version number into the documentation website
> 
> https://next.cloudinary.dev/
> 
> i was thinking we may be able to import the package.json from the package and reference the version number in the navigation or something

Ah, I see!

I got the wrong idea then. 

Adding it to the documentation website should be much easier since we have JavaScript. I will proceed with that.

**Comment by vickywane** [comment]
@colbyfayock I have made adjustments to this PR to add the current version from the `next-cloudinary` package into the hero component of the docs website. 

I have also removed the `markdown-magic` and `markdown-magic-package-json` packages. 

Screenshot 2024-10-14 at 22 40 54

**Comment by colbyfayock** [comment]
thanks for your contribution. this PR is eligible for free Cloudinary Hackatoberfest swag. Please send me an email at [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your name, GitHub username, and a link to the PR where I'll send further instructions.

Happy Hacktoberfest!

**Comment by colbyfayock** [comment]
@all-contributors please add @vickywane for doc

**Pull request merged**
