### PR TITLE
Include NextJS test app as pnpm workspace

### PR DESCRIPTION
**Pull request by Andarist**
This is a small internal improvement that I think is worth taking. This makes sure that the repository is using only a single package manager and switches away from using relative paths to reach out across workspace boundaries

cc @colbyfayock

### CODE REVIEW

**Comment by colbyfayock** [comment]
tbh, with this change, would it make sense to pull it into a top level directory? i liked the idea of it in the test dir simply for relating it to tests but that's not totally necessary and can instead be a "playground" of sorts, with the same functionality

additionally, i believe the docs are using relative pathing too, so might be an additional opportunity to fix those paths

https://github.com/cloudinary-community/next-cloudinary/blob/main/docs/pages/cldimage/basic-usage.mdx?plain=1#L4

likely something i can do tho to avoid burning time on it, or something i can open up as a new issue for Hacktoberfest or something

**Comment by Andarist** [comment]
> tbh, with this change, would it make sense to pull it into a top level directory?

It's really up to you as it's highly subjective. That's why I split this out of the other work.

> i liked the idea of it in the test dir simply for relating it to tests but that's not totally necessary and can instead be a "playground" of sorts, with the same functionality

Right, this is a playground of sorts right now. We could add some automated tests for this (like even a simple script and not a "traditional" test within jest/vitest/other framework) and it could still make sense to have this in `tests`.

I also just liked having the package name used by imports as with that I could be sure that I'm using the package how the user would use it so it gave me extra confidence in changes I was making.

> additionally, i believe the docs are using relative pathing too, so might be an additional opportunity to fix those paths

Ye, definitely. I'd certainly adjust those

**Comment by Andarist** [comment]
To fix the paths in the docs, we'd have to add a script to build the `next-cloudinary` package before the docs are build and deployed. I'm not sure where that can be done, I don't think that deploy is configured in the repo at all - perhaps it's managed entirely on Vercel?

**Comment by colbyfayock** [comment]
im actually already doing that! as i need to build the package before the files are available anyways

image

**Comment by colbyfayock** [comment]
looks like the CI is struggling to run the test:app suite

image

**Comment by colbyfayock** [comment]
merging into a beta with the other stuff as well

**Pull request merged**
