### PR TITLE
fix: removed ts-ignore

### LINKED ISSUE #426: [Bug] @ts-ignore in CldVideoPlayer.tsx
# **Bug Report**

## **Describe the bug**

A @ts-ignore is currently in place in the CldVideoPlayer component which is utilizing a videojs method to dispose of the player

https://github.com/cloudinary-community/next-cloudinary/blob/main/next-cloudinary/src/components/CldVideoPlayer/CldVideoPlayer.tsx#L227-L228

Goal would be to address whatever type issues are preventing this line from being removed.

There is a dispose method on the player itself but it was causing issues apparently. so the answer may be adding the type somewhere, which now exist inside of https://github.com/colbyfayock/cloudinary-util/blob/main/packages/types/src/types/cloudinary-video-player.d.ts

some context: https://github.com/cloudinary-community/next-cloudinary/pull/317#issuecomment-1779905842

### PR DESCRIPTION
**Pull request by Yash-sudo-web**
# Description

Removed ts-ignore from CldVideoPlayer.tsx

## Issue Ticket Number

Fixes #426 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Fix or improve the documentation
- [ ] This change requires a documentation update

# Checklist

- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have created an [issue](https://github.com/cloudinary-community/next-cloudinary/issues) ticket for this PR
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/cloudinary-community/next-cloudinary/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have run tests locally to ensure they all pass
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by colbyfayock** [comment]
@Yash-sudo-web the type has been released on @cloudinary-util/types@1.5.10

Can you update the dependency in this PR and confirm its working?

**Comment by Yash-sudo-web** [comment]
hey @colbyfayock , i tried installing @cloudinary-util/types@1.5.10, it was giving some other errors and the project was not running, but on  @cloudinary-util/types@1.5.8, i added the type by going into the node_modules folder and it was working fine, no errors were thrown

**Comment by colbyfayock** [comment]
ah, yeah thats an issue with how the /url-loader is built, if theres a version mismatch, it'll create an issue. i forced a version for the one dependency that was having an issue and updated both

**Comment by Yash-sudo-web** [comment]
oh okay, that makes sense, i thought maybe new versions for these deps would be officially released later or something
this should be good to go then?

**Comment by colbyfayock** [comment]
Yup, good to go, thank you!

**Comment by colbyfayock** [comment]
@all-contributors please add @Yash-sudo-web for code

**Comment by colbyfayock** [comment]
@Yash-sudo-web thanks for the contribution.

This PR is eligible for free Hacktoberfest swag!  Please send me an email with your name, GitHub username, and a link to this PR to hacktoberfest@cloudinary.com where I'll send further instructions.

**Pull request merged**
